name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ci-base.yml
    with:
      crystal-version: latest
